services:
  # --- 1. RTSP SERVER ---
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp_server
    ports:
      - "46458:8554"  # Cổng RTSP
    restart: always

  # --- 2. CAMERA SIMULATOR (Biến file video thành luồng Camera IP) ---
  camera_simulator:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    container_name: camera_simulator
    depends_on:
      - rtsp-server
    volumes:
      - ./samples:/samples:ro  # Mount thư mục samples của bạn vào
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ffmpeg -re -stream_loop -1 -err_detect ignore_err -i /samples/cam_1.mp4 -c:v libx264 -an -preset ultrafast -tune zerolatency -f rtsp rtsp://rtsp-server:8554/cam_1
      & ffmpeg -re -stream_loop -1 -err_detect ignore_err -i /samples/cam_2.mp4 -c:v libx264 -an -preset ultrafast -tune zerolatency -f rtsp rtsp://rtsp-server:8554/cam_2
      && wait"

  # --- 3. AI BACKEND ---
  api:
    build: .
    container_name: api_server
    depends_on:
      - rtsp-server # Đợi server RTSP lên trước
    command: uvicorn pythonFile.api_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: 
      - .env
    volumes:
      - ./snapshots:/app/snapshots
      - ./weights:/app/weights
      - /etc/localtime:/etc/localtime:ro  # Đồng bộ giờ với máy chủ
    environment:
      - TZ=Asia/Ho_Chi_Minh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always